---
- name: Common Setup.
  hosts: all
  become: true

  vars_files:
    - vaults/vault.yml

  roles:
    - name: Install PiP and Python dependencies.
      role: kevinnguyenhoang91.pip
      when: common_enabled | bool

    - name: Install Ansible.
      role: kevinnguyenhoang91.ansible
      when: common_enabled | bool

    - name: Common setup.
      role: common
      vars:
        users_enabled: true
        directories_enabled: true
        packages_enabled: true
      when: common_enabled | bool
