---
- name: Common Setup.
  hosts: all
  become: true

  vars_files:
    - vaults/vault.yml

  roles:
    - name: Common setup.
      role: common
      vars:
        users_enabled: true
        directories_enabled: true
        packages_enabled: true
      when: common_enabled | bool
