---
- name: Setup Docker
  hosts: all
  become: true
  tags:
    - docker
    - docker_setup

  vars_files:
    - vaults/vault.yml

  roles:
    - name: Install QEMU/KVM.
      role: docker
      vars:
        docker_install_enabled: true
        kvm_enabled: true
      when: docker_enabled | bool

- name: Setup Docker Private Registry.
  hosts: docker_registry
  become: true
  tags:
    - docker
    - docker_private_registry

  vars_files:
    - vaults/vault.yml

  roles:
    - name: Setup docker private registry.
      role: docker
      vars:
        docker_private_registry_enabled: true
      when: docker_enabled | bool
