---
- name: Setup rclone.
  hosts: all
  become: true
  tags:
    - rclone
    - rclone_setup

  vars_files:
    - vaults/vault.yml

  roles:
    - name: Setup rclone.
      role: rclone
      vars:
        rclone_install_enabled: true
