---
- name: Login docker private registry.
  become_user: "{{ machine_user }}"
  docker_login:
    registry: "{{ docker_private_registry_address }}"
    username: "{{ docker_private_registry_login_username }}"
    password: "{{ docker_private_registry_login_password }}"

- name: Login docker private registry.
  become_user: root
  docker_login:
    registry: "{{ docker_private_registry_address }}"
    username: "{{ docker_private_registry_login_username }}"
    password: "{{ docker_private_registry_login_password }}"
